#!/bin/bash
# JankyBorders の設定
# 色は 0xAARRGGBB 形式。See: https://github.com/FelixKratz/JankyBorders

options=(
  style=round
  width=5.0
  hidpi=on
  active_color=0xff7aa2f7
  inactive_color=0xff414868
)

borders "${options[@]}"
